# This is a basic workflow to help you get started with Actions

name: Homepage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master 

      # Runs a single command using the runners shell
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: ./master/docfx.json

      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
           BUILD_DIR: _site # docfx's default output directory is _site
           GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
